[app]
name = Arkanoid Roguelite
package = src
icon = 
version = 1.0.0
description = Arkanoid Roguelite - Pixel Edition

[build]
# Disable optimisation (keep asserts, docstrings) for easier debugging
optimize_level = 0

# Only bundle .py files (no .so, .dll, etc.)
include_patterns = *.py,*.wav,*.ogg
